### ISSUE TITLE
canvas drawing doesnt work clear

### ISSUE THREAD

**Issue by AydinTheFirst** [tuancc-repo/H5GG#11]
i setup canvas and it doesnt work clearly 
it renders different 

computer: 
![image](https://user-images.githubusercontent.com/84444757/177015200-402d92fa-6b24-4131-a2b2-4183fb09f88f.png)

phone :
![image](https://user-images.githubusercontent.com/84444757/177015208-8bdbcb1a-8e40-4271-96e8-e6132cb124c6.png)

edit: the question is how can i display it exact same size as phone

**Comment by tuancc-repo** [comment]
see H5DrawView.html

**Comment by tuancc-repo** [comment]
The height and width of the canvas need to be set to window.devicePixelRatio multiples of window.screen.height/width, and then zoom the canvas to 100% display, so that your drawing can be operated at the pixel level, and the obtained image will be clear
