### ISSUE TITLE
auto clicker method

### ISSUE THREAD

**Issue by AydinTheFirst** [tuancc-repo/H5GG#9]
is there any way to make an auto clicker

**Comment by tuancc-repo** [comment]
you can using Objective-C to write a h5gg plugin to do this, then you can call it on javascript by using h5gg.loadPlugin

**Comment by AydinTheFirst** [comment]
Is there an api or smth ?

**Comment by tuancc-repo** [comment]
see the h5gg plugin demo in /PluginDemo/customAlert/
